### ISSUE TITLE
Apache Agent Fails

### ISSUE THREAD

**Issue by arrmo** [librenms/librenms-agent#142]
Hi,

When I try to run the apache agent (agent-local/apache), all I get for an output is,
Data fetch failure.

Is there a way to help debug this?

Thanks!

**Comment by langerak** [comment]
Maybe try a "bash -x <script>" if it's a Bash script? That way you can verbosely see what part of the script is creating the error / output.

**Comment by arrmo** [comment]
OK, tried running the script (apache-status.py) manually - here is what I get,
Traceback (most recent call last):
  File "./apache-stats.py", line 38, in <module>
    user_agent = 'SNMP Apache Stats' )
  File "/usr/lib/python2.7/dist-packages/urlgrabber/grabber.py", line 755, in urlread
    return default_grabber.urlread(url, limit, **kwargs)
  File "/usr/lib/python2.7/dist-packages/urlgrabber/grabber.py", line 1211, in urlread
    s = self._retry(opts, retryfunc, url, limit)
  File "/usr/lib/python2.7/dist-packages/urlgrabber/grabber.py", line 1064, in _retry
    r = apply(func, (opts,) + args, {})
  File "/usr/lib/python2.7/dist-packages/urlgrabber/grabber.py", line 1194, in retryfunc
    fo = PyCurlFileObject(url, filename=None, opts=opts)
  File "/usr/lib/python2.7/dist-packages/urlgrabber/grabber.py", line 1259, in __init__
    self._do_open()
  File "/usr/lib/python2.7/dist-packages/urlgrabber/grabber.py", line 1599, in _do_open
    self._do_grab()
  File "/usr/lib/python2.7/dist-packages/urlgrabber/grabber.py", line 1737, in _do_grab
    raise e
urlgrabber.grabber.URLGrabError: [Errno 14] HTTPS Error 301 - Moved Permanently

But, if I go to http://localhost/server-status ... yep, stats are there. Thoughts?

Thanks!

**Comment by murrant** [comment]
um, is the script trying to get the stats via https?

**Comment by arrmo** [comment]
Why do you ask that? But in the end, it likely is ... my Apache server redirects all http to https.

Thanks!

**Comment by SNerone** [comment]
How is it that I go about fixing this issue as I'm have the same problem myself.
