### ISSUE TITLE
zfs-linux - Traceback - P = STATS["p"] - KeyError: 'p'

### ISSUE THREAD

**Issue by wriedel** [librenms/librenms-agent#561]
Hi,

running @zfs-testing on rocky linux Linux "9.5 (Blue Onyx)" 5.14.0-427.40.1.el9_4.x86_64

libnvpair3.x86_64                   2.2.6-1.el9                    @zfs-testing 
libuutil3.x86_64                    2.2.6-1.el9                    @zfs-testing 
libzfs5.x86_64                      2.2.6-1.el9                    @zfs-testing 
libzpool5.x86_64                    2.2.6-1.el9                    @zfs-testing 
zfs.x86_64                          2.2.6-1.el9                    @zfs-testing 
zfs-dkms.noarch                     2.2.6-1.el9                    @zfs-testing 
zfs-release.noarch                  2-3.el9                        @@commandline

I get this results:

/usr/bin/sudo /etc/snmp/zfs-linux
Traceback (most recent call last):
  File "/etc/snmp/zfs-linux", line 288, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/etc/snmp/zfs-linux", line 79, in main
    P = STATS["p"]
KeyError: 'p'

Here my arcstats:

cat /proc/spl/kstat/zfs/arcstats
9 1 0x01 147 39984 7410849971 6851678728036
name                            type data
hits                            4    2291773
iohits                          4    1442
misses                          4    21417
demand_data_hits                4    5208
demand_data_iohits              4    0
demand_data_misses              4    4170
demand_metadata_hits            4    2207613
demand_metadata_iohits          4    777
demand_metadata_misses          4    15966
prefetch_data_hits              4    0
prefetch_data_iohits            4    0
prefetch_data_misses            4    0
prefetch_metadata_hits          4    78952
prefetch_metadata_iohits        4    665
prefetch_metadata_misses        4    1281
mru_hits                        4    201916
mru_ghost_hits                  4    0
mfu_hits                        4    2089857
mfu_ghost_hits                  4    0
uncached_hits                   4    0
deleted                         4    64
mutex_miss                      4    0
access_skip                     4    0
evict_skip                      4    6
evict_not_enough                4    0
evict_l2_cached                 4    0
evict_l2_eligible               4    1696256
evict_l2_eligible_mfu           4    196608
evict_l2_eligible_mru           4    1499648
evict_l2_ineligible             4    4096
evict_l2_skip                   4    0
hash_elements                   4    47740530
hash_elements_max               4    47758728
hash_collisions                 4    13621854
hash_chains                     4    10721472
hash_chain_max                  4    8
meta                            4    1073741824
pd                              4    2147483648
pm                              4    2147483648
c                               4    214748364800
c_min                           4    214748364800
c_max                           4    322122547200
size                            4    5388592472
compressed_size                 4    132657664
uncompressed_size               4    544652288
overhead_size                   4    540914688
hdr_size                        4    6517680
data_size                       4    68550656
metadata_size                   4    605021696
dbuf_size                       4    26970384
dnode_size                      4    62532216
bonus_size                      4    35077248
anon_size                       4    0
anon_data                       4    0
anon_metadata                   4    0
anon_evictable_data             4    0
anon_evictable_metadata         4    0
mru_size                        4    450284544
mru_data                        4    67100160
mru_metadata                    4    383184384
mru_evictable_data              4    1536
mru_evictable_metadata          4    28672
mru_ghost_size                  4    0
mru_ghost_data                  4    0
mru_ghost_metadata              4    0
mru_ghost_evictable_data        4    0
mru_ghost_evictable_metadata    4    0
mfu_size                        4    223287808
mfu_data                        4    1450496
mfu_metadata                    4    221837312
mfu_evictable_data              4    0
mfu_evictable_metadata          4    45056
mfu_ghost_size                  4    0
mfu_ghost_data                  4    0
mfu_ghost_metadata              4    0
mfu_ghost_evictable_data        4    0
mfu_ghost_evictable_metadata    4    0
uncached_size                   4    0
uncached_data                   4    0
uncached_metadata               4    0
uncached_evictable_data         4    0
uncached_evictable_metadata     4    0
l2_hits                         4    7500
l2_misses                       4    13861
l2_prefetch_asize               4    868352
l2_mru_asize                    4    2751906279424
l2_mfu_asize                    4    121454174208
l2_bufc_data_asize              4    2868635279360
l2_bufc_metadata_asize          4    4726042624
l2_feeds                        4    6664
l2_rw_clash                     4    0
l2_read_bytes                   4    48028160
l2_write_bytes                  4    883712
l2_writes_sent                  4    144
l2_writes_done                  4    144
l2_writes_error                 4    0
l2_writes_lock_retry            4    0
l2_evict_lock_retry             4    0
l2_evict_reading                4    0
l2_evict_l1cached               4    0
l2_free_on_write                4    0
l2_abort_lowmem                 4    0
l2_cksum_bad                    4    0
l2_io_error                     4    0
l2_size                         4    4935949341696
l2_asize                        4    2873185970688
l2_hdr_size                     4    4580795808
l2_log_blk_writes               4    0
l2_log_blk_avg_asize            4    21895
l2_log_blk_asize                4    916889600
l2_log_blk_count                4    46721
l2_data_to_meta_ratio           4    3322
l2_rebuild_success              4    3
l2_rebuild_unsupported          4    0
l2_rebuild_io_errors            4    0
l2_rebuild_dh_errors            4    0
l2_rebuild_cksum_lb_errors      4    0
l2_rebuild_lowmem               4    0
l2_rebuild_size                 4    4938936130048
l2_rebuild_asize                4    2876132065280
l2_rebuild_bufs                 4    47748862
l2_rebuild_bufs_precached       4    1874
l2_rebuild_log_blks             4    46721
memory_throttle_count           4    0
memory_direct_count             4    0
memory_indirect_count           4    0
memory_all_bytes                4    405089136640
memory_free_bytes               4    396172697600
memory_available_bytes          3    383010345600
arc_no_grow                     4    0
arc_tempreserve                 4    0
arc_loaned_bytes                4    0
arc_prune                       4    0
arc_meta_used                   4    5316915032
arc_dnode_limit                 4    32212254720
async_upgrade_sync              4    101
predictive_prefetch             4    80829
demand_hit_predictive_prefetch  4    999
demand_iohit_predictive_prefetch 4    297
prescient_prefetch              4    69
demand_hit_prescient_prefetch   4    63
demand_iohit_prescient_prefetch 4    6
arc_need_free                   4    0
arc_sys_free                    4    13162352000
arc_raw_size                    4    0
cached_only_in_progress         4    0
abd_chunk_waste_size            4    3126784

**Comment by VVelox** [comment]
Try `https://github.com/librenms/librenms-agent/blob/master/snmp/zfs`. This is basically the current ZFS extend supporting both FreeBSD and Linux.
